web/router.ex
defmodule BandIndigo.Router do
  use BandIndigo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BandIndigo do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/discography", DiscographyController, :index
    get "/band", BandController, :index
    get "/photo", PhotoController, :index
  end
end

lib/band_indigo/endpoint.ex
defmodule BandIndigo.Endpoint do
  use Phoenix.Endpoint, otp_app: :band_indigo

  socket "/socket", BandIndigo.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :band_indigo, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_band_indigo_key",
    signing_salt: "njcc89FN"

  plug BandIndigo.Router
end

lib/band_indigo/repo.ex
defmodule BandIndigo.Repo do
  use Ecto.Repo, otp_app: :band_indigo
end

web/models/disk.ex
defmodule BandIndigo.Disk do
  use BandIndigo.Web, :model
  use Ecto.Schema
  import Ecto.Query

  schema "disks" do
    field :name,             :string
    field :year,             Ecto.Date
    field :label,            :string
    field :cover_name,       :string
    field :itunes_link,      :string
    field :google_play_link, :string
    field :amazon_link,      :string
    has_many :tracks,        BandIndigo.Track

    timestamps
  end

  @required_fields ~w(name year label cover_name)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/track.ex
defmodule BandIndigo.Track do
  use BandIndigo.Web, :model
  use Ecto.Schema

  schema "tracks" do
    field :name, :string
    field :duration, Ecto.Time
    field :order, :integer
    belongs_to :disk, BandIndigo.Disk

    timestamps
  end

  @required_fields ~w(name duration)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/band_controller.ex
defmodule BandIndigo.BandController do
  use BandIndigo.Web, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

web/controllers/diskography_controller.ex
defmodule BandIndigo.DiscographyController do
  use BandIndigo.Web, :controller
  import Ecto.Query

  alias BandIndigo.Repo
  alias BandIndigo.Track
  alias BandIndigo.Disk

  def index(conn, _params) do
    disks = Disk
    |> Ecto.Query.order_by(desc: :year)
    |> Repo.all
    |> Repo.preload(tracks: from(t in Track, order_by: t.order))
    render(conn, "index.html", disks: disks)
  end
end

web/controllers/page_controller.ex
defmodule BandIndigo.PageController do
  use BandIndigo.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/photo_controller.ex
defmodule BandIndigo.PhotoController do
  use BandIndigo.Web, :controller

  def index(conn, _params) do
    {:ok, access_token} = Application.fetch_env(:elixtagram, :access_token)
    Elixtagram.configure
    Elixtagram.configure(:global, access_token)
    user = Elixtagram.user(:self, :global)
    if user.id == "2953237909" do
      media = Elixtagram.user_recent_media(:self, %{count: 100})
      data = %{ user: user, media: media, is_authenticated: true }
      render conn, "index.html", data: data
    else
      render conn, "500.html"
    end
  end
end

web/views/band_view.ex
defmodule BandIndigo.BandView do
  use BandIndigo.Web, :view

  def title do
    "Band"
  end
end

web/views/discography_view.ex
defmodule BandIndigo.DiscographyView do
  use BandIndigo.Web, :view

  def title do
    "Discography"
  end
end

web/views/error_view.ex
defmodule BandIndigo.ErrorView do
  use BandIndigo.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule BandIndigo.LayoutView do
  use BandIndigo.Web, :view

  def title(conn) do
    case conn.path_info do
      [] -> "Band Indigo — Instrumental Rock From Siberia"
      _ ->
        "Band Indigo: #{String.capitalize(hd conn.path_info)}"
    end
  end

  def active_class(conn, path) do
    current_path = Path.join(["/" | conn.path_info])
    if path == current_path do
      "active"
    else
      nil
    end
  end
end

web/views/page_view.ex
defmodule BandIndigo.PageView do
  use BandIndigo.Web, :view
end

web/views/photo_view.ex
defmodule BandIndigo.PhotoView do
  use BandIndigo.Web, :view
end

web/templates/band/index.html.eex
<div class="band-info">
<h1>About</h1>
<p>Indigo is an instrumental playing band based in Novosibirsk, Russia.</p>
<p>
  Indigo was formed in August, 5 2005 by three persons: Timofey Streltsov (guitars), Tatiana Arisova (bass) and Roman Sotnikov (drums &amp; percussion)
</p>
<p>
  Since 2005 they had recorded published two full albums and have third in production.
</p>
<p>
  You may reach Indigo by email <a href="mailto:info@band-indigo.com">info@band-indigo.com</a>
</p>
<p>
  Hope you will enjoy the music!
</p>
</div>

<div class="center-block social">
<a href="https://www.facebook.com/band.indigo.nsk">
<img src="/images/facebook.svg" alt="facebook" width="50" border="0"/>
</a>

<a href="https://www.youtube.com/channel/UCK-CRSAuJoMmSyKFFPtJphw">
<img src="/images/youtube.svg" alt="youtube" width="50"/>
</a>

<a href="https://www.instagram.com/band_indigo_com/?ref=badge">
<img src="/images/instagram.svg" alt="youtube" width="50"/>
</a>
</div>

web/templates/discography/index.html.eex
<div class="small-content">
  <h1>Discography</h1>
  <h2>Here you can find info about our distributed music.</h2>
</div>
<%= for disk <- @disks do %>
  <div class="row">
    <div class="disk-wrapper">
      <h3><%= Calendar.Strftime.strftime!(disk.year, "%Y") <> " " <> disk.name %></h3>
      <div class="cells">
        <div class="cell cover-wrapper">
          <img class="cover" src="<%= "/images/" <> disk.cover_name %>" alt="<%= disk.cover_name%>"/>
        </div> <!-- cover cell -->

        <div class="cell">
          <div class="tracks-wrapper">
            <ol class="tracks-list">
              <%= for track <- disk.tracks do %>
                <li>
                  <span><%= track.name %></span>
                  <span class="line"></span>
                  <span class="duration">
                    <%= Calendar.Strftime.strftime!(track.duration, "%M:%S") %>
                  </span>
                </li>
              <% end %>
            </ol>
          </div> <!-- tracks-wrapper -->
        </div> <!-- tracks cell -->
      </div> <!-- cells -->
      <div class="store-links">
        <a href="<%= disk.itunes_link %>">Buy it on iTunes</a>
        <a href="<%= disk.google_play_link %>">Buy it on Google Play</a>
        <!--<a href="<%= disk.amazon_link %>">Buy it on Amazon</a>-->
      </div>
    </div> <!-- disk-wrapper -->
  </div> <!-- row -->
<% end %>

web/templates/discography/show.html.eex
<h3>
  <%= @disk.name %>
  <span><%= @disk.year |> Calendar.Strftime.strftime!("%Y") %></span>
</h3>
<div class="disk-wrapper">
  <img class="cover" src="<%= "/images/" <> @disk.cover_name %>"/>
  <div class="tracks"></div>
  <ol>
    <%= for track <- @disk.tracks do %>
      <li>
        <span class="name"><%= track.name %></span>
        <span class="duration"><%= track.duration |> Calendar.Strftime.strftime!("%M:%S") %></span>
      </li>
    <% end %>
  </ol>
</div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="description" content="Band Indigo landing page"/>
    <meta name="keywords" content="Bank Indigo, music, Instrumental rock, instrumental, rock, iTunes, Google Play, Amazon"/>
    <meta name="robots" content="index, follow"/>
    <meta name="author" content="Roman Sotnikov"/>

    <title><%= title(@conn) %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=422989191054100";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <div class="container" role="main">
      <div class="header">
        <div class="index-logo-wrapper">
          <img src="/images/indigo_logo_white.svg" class="main-logo" alt="band indigo logo"/>
        </div>
        <ul class="nav nav-pills">
          <li>
            <%= link "Home", to: page_path(@conn, :index),
                             class: active_class(@conn, page_path(@conn, :index)) %>
            </li>
          <li>
            <%= link "Band", to: band_path(@conn, :index),
                             class: active_class(@conn, band_path(@conn, :index)) %>
          </li>
          <li>
            <%= link "Music", to: discography_path(@conn, :index),
                              class: active_class(@conn, discography_path(@conn, :index)) %>
          </li>
          <li>
            <%= link "Photo", to: photo_path(@conn, :index),
                              class: active_class(@conn, photo_path(@conn, :index)) %>
          </li>
        </ul>
      </div>

      <%= render @view_module, @view_template, assigns %>

      <div class="bottom">
        <div class="fb-like" data-href="https://www.facebook.com/band.indigo.nsk" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>
        <div class="tw-share"><a href="https://twitter.com/share" class="twitter-share-button" data-via="retgoat">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>
      </div>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-22209072-3', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="indigo-photo-wrapper">
  <img src="/images/indigo-photo.jpg" alt="Band Indigo"/>
</div>
<div class="slogan-wrapper">
  <h1>Band Indigo &mdash; instrumental rock from Siberia</h1>
  <h2>Get our music on iTunes, Google play.</h2>
</div>

<div class="store-logos">
  <a href="https://itunes.apple.com/ru/album/chain-reaction/id1220467986?l=en">
    <img src="/images/itunes.png" alt="Available on iTunes" />
  </a>

  <a href="https://play.google.com/store/music/album?id=Bzcj5qo6bakwzmyqsremohexe7m&hl=en">
    <img src="/images/google_play.png" alt="Get it in Google Play"/>
  </a>
</div>

web/templates/photo/500.html.eex
<h1>Error occured</h1>
<p>
  Oops, it seems site is broken. Don't worry we already working on ot.
</p>
<p>
  Visit <a href="/">home</a> page and take a look on other stuff while we are managing it.
</p>

web/templates/photo/index.html.eex
<div class="popup-gallery">
  <%= for picture <- @data.media do %>
    <a href="<%= picture.images.standard_resolution.url %>">
      <img class="img-rounded" alt="Photo" src="<%= picture.images.low_resolution.url %>" style="width: 140px; height: 140px; margin: 10px">
    </a>
  <% end %>
</div>